/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coin.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Coin(props) {
  const { nodes, materials } = useGLTF('/models/coin.glb')
  return (
    <group {...props} dispose={null} scale={[5, 5, 5]}>
      <mesh geometry={nodes['tripo_node_dbc46e65-513d-4e23-9067-beb8138cad7d'].geometry} material={materials['tripo_mat_dbc46e65-513d-4e23-9067-beb8138cad7d']} />
    </group>
  )
}

useGLTF.preload('/models/coin.glb')
